// Generated by ./build-aux/bin/authors.h-gen, do not edit by hand.

#define PACKAGE_SHORT_AUTHORS \


#define PACKAGE_AUTHORS \
  "Jean Fechter    <jean.fechter@epita.fr>\n"                                \
  "Vasco Sampaio   <vasco.sampaio@epita.fr>\n"                               \
  "Theo Crepin     <theo.crepin@epita.fr>\n"                                 \
  "Thibault Boutet <thibault.boutet@epita.fr>\n"
